url: ''
baseurl: ''
google-tracking-id: ''
force-https: true
lang: en
author: John Smith
title: '{ John Smith }'
description: >-
  Blog and website of John Smith, blogging mainly for tech. Opinions expressed
  are mine.
keywords: 'smith, jones, personal, jekyll, theme'
favicon: /img/favicon.ico
black-favicon: /img/black-lab-glass.ico
logo: /img/author.png
background-img: ../img/intro-bg.jpg
dynamic-typing: true
shuffle: true
loop: true
loop-count: false
type-speed: 10
start-delay: 200
delete-delay: 5000
lines:
  - text: 'The lower you fall, the higher you''ll fly.'
  - text: Where’s your will to be weird?
me-img: /img/jetpacktocat.png
color-browser: '#000000'
apple-status-bar-style: black
web-app-mode: true
icon-36p: /img/web-app/icon-36p.png
icon-48p: /img/web-app/icon-48p.png
icon-72p: /img/web-app/icon-72p.png
icon-96p: /img/web-app/icon-96p.png
icon-144p: /img/web-app/icon-144p.png
icon-192p: /img/web-app/icon-192p.png
enable-gesture-navigation: true
post-preview-words: 96
paginate: 5
email-share: true
fb-share: true
twitter-share: true
linkedin-share: true
reddit-share: true
google-plus-share: true
tumblr-share: true
pinterest-share: true
pocket-share: true
vkontakte-share: true
disqus-shortname: personal-jekyll-theme
syntax-highlight: true
events:
  - image: /img/timeline/spidertocat.png
    date: September 2013 - Today
    description: Saving the neighborhood!
  - image: /img/timeline/baracktocat.jpg
    date: September 2007 - August 2013
    description: Started coding
timeline-img: /img/timeline/default.png
email: your@email.here
pgp: false
author_blurb: >-
  John Smith is an awesome person. He lives in Flatland, where he works on
  two-dimensional engineering projects. In his spare time, John likes to eat
  cotton candy.
author_blurb_image: /img/author.png
social:
  - title: facebook
    url: 'https://facebook.com/'
  - title: twitter
    url: 'https://twitter.com/'
  - title: github
    url: 'https://github.com/PanosSakkos/personal-jekyll-theme'
  - title: bitcoin
    url: 'https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi'
  - title: rss
    url: /feed.xml
err-404-img: /img/labtocat.png
keybase-username: johnsmith
keybase-in-social: true
keybase-in-footer: true
pages_list:
  About: about
  Blog: latest-post
  Timeline: timeline
  Contact: contact
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
paginate_path: 'blog/page:num/'
sass:
  style: compressed
gems:
  - jekyll-paginate
  - jemoji
